version: '2.1'

services:
  dropbox_client:
    build: .
    image: dropbox_client
    container_name: dropbox_client
    stdin_open: true
    tty: true
    volumes:
      - "data_dropbox:/root/dropbox"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "5000:5000"
    networks:
      - dropbox

volumes:
  data_dropbox:

networks:
  dropbox:
